import Head from 'next/head';
import { useState } from 'react';
import { v4 as uuidv4 } from 'uuid';
// styles
import { DashboardStyle } from '@/styles/dashboard';
import { GlobalStyles } from '@/styles/global';
import { AssetsStyle } from '@/styles/general';
import { ButtonStyle } from '@/styles/widgets';
// components
import NavigationComponent from '@/components/navigation';
import UploadComponent from '@/components/upload';
import PreviewComponent from '@/components/preview';
import TableComponent from '@/components/table';


const Home = () => {
  const [open, setOpen] = useState(false);
  const handleOpen = () => setOpen(true);
  const handleClose = () => setOpen(false);
  const [value, updateValue]: any = useState({
    noteType: null,
    client: '',
  });

  let [notes, updateNotes]: any = useState([]);

  const uploadAction = () => {
    updateNotes([
      ...notes, 
      { ...value, id: uuidv4() }
    ]);
  }

  const removeItem = (id: string) => {
    const newArray = notes.filter((item: any) => item.id !== id);
    updateNotes(newArray);
  }

  return (
    <>
      <Head>
        <title>Mentalyc Web App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <GlobalStyles />
      <DashboardStyle.app>
        <NavigationComponent />
        <AssetsStyle.section>
          <AssetsStyle.info>
            <a>Hi, Maria</a>
            <AssetsStyle.faqIcon />
          </AssetsStyle.info>
          <DashboardStyle.title>Upload your session’s recordings</DashboardStyle.title>
          <ButtonStyle.wrapper onClick={handleOpen}>Upload</ButtonStyle.wrapper>
        </AssetsStyle.section>
        {notes.length > 0 && (
          <>
            <AssetsStyle.section>
              <PreviewComponent count={notes.length} />
            </AssetsStyle.section>
            <AssetsStyle.section>
              <TableComponent removeItem={removeItem} data={notes} />
            </AssetsStyle.section>
          </>
        )}
        
        <UploadComponent
          open={open}
          handleClose={handleClose}
          value={value}
          updateValue={updateValue}
          uploadAction={uploadAction}
        />
      </DashboardStyle.app>
    </>
  )
}

export default Home;